// 389. Find the Difference
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

public class Solution
{
    public char FindTheDifference(string s, string t)
    {
        if (s.Length == 0)
            return t[0];
        char result = s[0];
        for (int i = 1; i < s.Length; i++)
        {
            result ^= s[i];
        }
        for (int i = 0; i < t.Length; i++)
        {
            result ^= t[i];
        }
        return result;
    }
}